version: 2.0

jobs:
  Python_2.7:
      docker:
        - image: circleci/python:2.7
      steps: &steps
        - checkout
        - run: pip install -r requirements.txt
        - run: pip install pytest
        - run: python --version ; pip --version ; pwd ; ls
        - run: pytest
  Python_3.6:
      docker:
        - image: circleci/python:3.6
      steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - Python_2.7
      - Python_3.6